<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
   public function run(): void
    {
        DB::table('currencies')->insert([
            [
                'id' => 1,
                'name' => 'USD',
                'symbol' => '$',
                'code' => 'USD',
                'rate' => 1,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 1,
                'is_default' => 'Yes',
                'is_active' => 'Yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'GBP',
                'symbol' => '£',
                'code' => 'GBP',
                'rate' => 0.74,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 3,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'SAR',
                'symbol' => null,
                'code' => 'SAR',
                'rate' => 3.75075,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'EUR',
                'symbol' => '€',
                'code' => 'EUR',
                'rate' => 0.911505,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'PKR',
                'symbol' => null,
                'code' => 'PKR',
                'rate' => 156.75,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'AUD',
                'symbol' => '$',
                'code' => 'AUD',
                'rate' => 1.4889,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'PHP',
                'symbol' => null,
                'code' => 'PHP',
                'rate' => 52.158,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'SGD',
                'symbol' => null,
                'code' => 'SGD',
                'rate' => 1.3908,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'JPY',
                'symbol' => null,
                'code' => 'JPY',
                'rate' => 106.191,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'INR',
                'symbol' => null,
                'code' => 'INR',
                'rate' => 71.989,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'CNY',
                'symbol' => null,
                'code' => 'CNY',
                'rate' => 7.17209,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'TRY',
                'symbol' => null,
                'code' => 'TRY',
                'rate' => 5.8221,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'RUB',
                'symbol' => null,
                'code' => 'RUB',
                'rate' => 64.34,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'AED',
                'symbol' => null,
                'code' => 'AED',
                'rate' => 3.7,
                'decimals' => 2,
                'symbol_placement' => 'before',
                'primary_order' => 0,
                'is_default' => 'No',
                'is_active' => 'Yes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
